-- MySQL Script generated by MySQL Workbench
-- Wed Jan 21 18:23:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carrofacil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `carros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carros` ;

CREATE TABLE IF NOT EXISTS `carros` (
  `carros_id` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(255) NOT NULL,
  `marca` VARCHAR(255) NOT NULL,
  `ano` INT NOT NULL,
  `placa` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`carros_id`),
  UNIQUE INDEX `placa` (`placa` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientes` ;

CREATE TABLE IF NOT EXISTS `clientes` (
  `clientes_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`clientes_id`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locacoes` ;

CREATE TABLE IF NOT EXISTS `locacoes` (
  `locacoes_id` INT NOT NULL AUTO_INCREMENT,
  `clientes_id` INT NOT NULL,
  `carros_id` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`locacoes_id`),
  INDEX `clientes_id` (`clientes_id` ASC) VISIBLE,
  INDEX `carros_id` (`carros_id` ASC) VISIBLE,
  CONSTRAINT `locacoes_ibfk_1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `clientes` (`clientes_id`),
  CONSTRAINT `locacoes_ibfk_2`
    FOREIGN KEY (`carros_id`)
    REFERENCES `carros` (`carros_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pagamentos` ;

CREATE TABLE IF NOT EXISTS `pagamentos` (
  `pagamentos_id` INT NOT NULL AUTO_INCREMENT,
  `locacoes_id` INT NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  `valor_pago` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`pagamentos_id`),
  INDEX `locacoes_id` (`locacoes_id` ASC) VISIBLE,
  CONSTRAINT `pagamentos_ibfk_1`
    FOREIGN KEY (`locacoes_id`)
    REFERENCES `locacoes` (`locacoes_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Placeholder table for view `vw_pagamentos_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vw_pagamentos_clientes` (`pagamentos_id` INT, `clientes` INT, `locacoes_id` INT, `data_pagamento` INT, `valor_pago` INT);

-- -----------------------------------------------------
-- Placeholder table for view `vw_relatorio_locacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vw_relatorio_locacoes` (`cliente` INT, `carro` INT, `data_inicio` INT, `data_fim` INT, `valor` INT);

-- -----------------------------------------------------
-- View `vw_pagamentos_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vw_pagamentos_clientes`;
DROP VIEW IF EXISTS `vw_pagamentos_clientes` ;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `vw_pagamentos_clientes` AS select `p`.`pagamentos_id` AS `pagamentos_id`,`c`.`nome` AS `clientes`,`l`.`locacoes_id` AS `locacoes_id`,`p`.`data_pagamento` AS `data_pagamento`,`p`.`valor_pago` AS `valor_pago` from ((`pagamentos` `p` join `locacoes` `l` on((`p`.`locacoes_id` = `l`.`locacoes_id`))) join `clientes` `c` on((`l`.`clientes_id` = `c`.`clientes_id`)));

-- -----------------------------------------------------
-- View `vw_relatorio_locacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vw_relatorio_locacoes`;
DROP VIEW IF EXISTS `vw_relatorio_locacoes` ;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `vw_relatorio_locacoes` AS select `c`.`nome` AS `cliente`,`ca`.`modelo` AS `carro`,`l`.`data_inicio` AS `data_inicio`,`l`.`data_fim` AS `data_fim`,`l`.`valor` AS `valor` from ((`locacoes` `l` join `clientes` `c` on((`l`.`clientes_id` = `c`.`clientes_id`))) join `carros` `ca` on((`l`.`carros_id` = `ca`.`carros_id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
